//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by T3ED.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_BLOCKNUM           101
#define ID_INDICATOR_SCROLLMODE         103
#define ID_INDICATOR_CORDINATES         104
#define ID_INDICATOR_PASTEMODE          105
#define IDR_MAINFRAME                   128
#define IDR_T3EDTYPE                    129
#define IDD_SMOOTHING1                  132
#define IDD_SMOOTHING2                  133
#define IDD_TEXTURES                    135
#define IDD_LOADING_QFS                 136
#define IDD_NEWOBJECT                   137
#define IDD_POLYFLAGS                   138
#define IDD_CLEARTRACK                  140
#define IDD_TEXTUREPROPS                141
#define IDC_ROTATE                      144
#define IDC_MOVE                        147
#define IDB_BACKIMAGE                   153
#define IDD_TRKBLOCK_DIALOG             154
#define IDD_LSPROPS                     156
#define IDD_LOD_GENERATION              161
#define IDD_ADJUSTVR                    162
#define IDD_RAYTRACE                    165
#define IDD_LOD_STARTEND                166
#define IDD_Expand                      167
#define IDD_ROTATE                      169
#define IDD_BLOCKPASTE                  170
#define IDD_OBJPOLYPROPS                173
#define IDD_EXTRAOBJPROPS               174
#define IDD_EXPANDBLOCK                 175
#define IDD_MOVETO                      176
#define IDD_BLOCK_PROPS                 177
#define IDD_FILE_PROPERTIES             178
#define IDD_VROAD_HEIGHTS_SPDFILES      179
#define IDD_FINDPOLYGON                 181
#define IDD_SET_VISI                    183
#define IDC_COPYRIGHT                   1000
#define IDC_COPYRIGHT2                  1001
#define IDC_COPYRIGHT3                  1002
#define IDC_COPYRIGHT4                  1003
#define IDC_COPYRIGHT5                  1004
#define IDC_CHECK1                      1008
#define IDC_SMOOTH1_STATIC1             1009
#define IDC_CHECK_HEIGHTS               1009
#define IDC_SMOOTH1_STATIC2             1010
#define IDC_CHECK3                      1010
#define IDC_CHECK_SPDFA                 1010
#define IDC_SMOOTH1_STATIC3             1011
#define IDC_CHECK4                      1011
#define IDC_CHECK_SPDRA                 1011
#define IDC_SMOOTH1_STATIC4             1012
#define IDC_CHECK5                      1012
#define IDC_EDIT2                       1013
#define IDC_CHECK6                      1013
#define IDC_EDIT1                       1014
#define IDC_CHECK8                      1014
#define IDC_EDIT_END                    1014
#define IDC_BITMAP                      1015
#define IDC_CHECK7                      1015
#define IDC_ANIMDURATION                1015
#define IDC_EDITEND                     1015
#define IDC_EDIT_ENDBL                  1015
#define IDC_SPIN1                       1016
#define IDC_EDIT7                       1016
#define IDC_NUMBMP                      1017
#define IDC_CHECK9                      1017
#define IDC_FILEOPEN                    1018
#define IDC_CHECK10                     1018
#define IDC_PROGRESS1                   1019
#define IDC_EDIT8                       1019
#define IDC_RADIO1                      1020
#define IDC_RADIO2                      1021
#define IDC_CHUNK0                      1022
#define IDC_CHUNK1                      1023
#define IDC_CHUNK2                      1024
#define IDC_CHUNK3                      1025
#define IDC_BROWSE                      1026
#define IDC_CHECK2                      1027
#define IDC_CHECK_ANIMATED              1028
#define IDC_COMBO1                      1029
#define IDC_CHECK_PVRFLAGS              1029
#define IDC_BROWSE6                     1031
#define IDC_BROWSE7                     1032
#define IDC_EDIT6                       1033
#define IDC_HSPROPS                     1034
#define IDC_ROTNONE                     1035
#define IDC_ROT90                       1036
#define IDC_ROT180                      1037
#define IDC_ROT270                      1038
#define IDC_TILINGNONE                  1039
#define IDC_TILINGHOR2                  1040
#define IDC_TILINGHOR4                  1041
#define IDC_TILINGVERT2                 1042
#define IDC_TILINGVERT4                 1043
#define IDC_FLIPH                       1044
#define IDC_FLIPV                       1045
#define IDC_TWOSIDED                    1046
#define IDC_NEIGHBOUR_EDIT1             1046
#define IDC_ANIMTEX                     1047
#define IDC_ANIMLENGTH                  1051
#define IDC_CHECK11                     1052
#define IDC_NEIGHBOUR_EDIT2             1053
#define IDC_NEIGHBOUR_EDIT3             1054
#define IDC_NEIGHBOUR_EDIT4             1055
#define IDC_CHECK13                     1055
#define IDC_NEIGHBOUR_EDIT5             1056
#define IDC_NEIGHBOUR_EDIT6             1057
#define IDC_NEIGHBOUR_EDIT7             1058
#define IDC_PROGRESS2                   1058
#define IDC_NEIGHBOUR_EDIT8             1059
#define IDC_RADIO5                      1063
#define IDC_RADIO6                      1064
#define IDC_RADIO7                      1065
#define IDC_ADJUSTMETHOD                1066
#define IDC_STATIC_URL                  1069
#define IDC_RADIO8                      1069
#define IDC_EDITSTART                   1070
#define IDC_EDIT3                       1071
#define IDC_EDIT4                       1072
#define IDC_CHECKTrack                  1073
#define IDC_CHECKObjects                1074
#define IDC_CHECKExtraObjects           1075
#define ID_LABEL                        1076
#define IDC_TEXT1                       1077
#define IDC_EDIT_BLOCK                  1078
#define IDC_CHECK_CONNECT               1079
#define IDC_EDIT_OBJNUM                 1079
#define IDC_EDITX                       1080
#define IDC_EDIT_NUMPOLY                1080
#define IDC_EDITY                       1081
#define IDC_EDIT_CHUNK                  1081
#define IDC_EDITWIDTH                   1081
#define IDC_EDITHEIGHT                  1082
#define IDC_EDIT_REFX_UK1               1082
#define IDC_EDITZ                       1083
#define IDC_EDIT_X                      1083
#define IDC_EDIT_Y                      1084
#define IDC_EDIT_Z                      1085
#define IDC_RADIOTOP                    1086
#define IDC_EDIT_NVERTICES              1086
#define IDC_RADIOMIDDLE                 1087
#define IDC_EDIT_REFX_UK2               1087
#define IDC_EDIT_NMEDVERT               1087
#define IDC_RADIOBOTTOM                 1088
#define IDC_EDIT_REFX_UK3               1088
#define IDC_EDIT_NHIGHVERT              1088
#define IDC_EDIT_ANGLE                  1089
#define IDC_EDIT_NLOWVERT               1089
#define IDC_RADIO_ADD_REPLACE1          1090
#define IDC_EDIT_XOBJ_UK                1090
#define IDC_EDIT_NSOUNDSRC              1090
#define IDC_EDIT_XOBJ_ANIM_MEM          1091
#define IDC_EDIT_NLIGHTSRC              1091
#define IDC_RADIO_ADD_REPLACE3          1091
#define IDC_TEXT_ENDBL                  1092
#define IDC_EDIT_XOBJ_ANIMDELAY         1092
#define IDC_RADIO_ADD_REPLACE4          1092
#define IDC_RTEXT                       1093
#define IDC_CHECK_MOVE                  1094
#define IDC_CHECK_ROTATE                1095
#define IDC_CHECK_MOVEZ                 1096
#define IDC_EDITLENGTH                  1096
#define IDC_CHECK_EXPAND_WIDTH          1097
#define IDC_CHECKNOSMOOTH               1097
#define IDC_CHECK_EXPAND_LENGHT         1098
#define IDC_CHECK_MERGE                 1098
#define IDC_EDIT_DIST                   1099
#define IDC_CHECK_PASTEVROAD            1099
#define IDC_COMBO_XOBJTYPE              1100
#define IDC_CHECK_PASTEBLOCK            1100
#define IDC_COMBO_CROSSTYPE             1101
#define IDC_TXT_ENDBLOCK                1102
#define IDC_COMBO_RECENTER              1102
#define IDC_EDIT_ENDBLOCK               1103
#define IDC_COMBO_ANIML                 1103
#define IDC_EDIT_STARTBLOCK             1104
#define IDC_TXT_REFX_UK1                1104
#define IDC_TXT_STARTBLOCK              1105
#define IDC_TXT_REFX_UK2                1105
#define IDC_TXT_REFX_UK3                1106
#define IDC_CHECK_RECENTER              1107
#define IDC_CHECK_PASTEHEIGHTS          1107
#define IDC_COMBO_XOBJ_UK3              1108
#define IDC_CHECK_PASTESPDFA            1108
#define IDC_CHECK_CONVERT               1109
#define IDC_CHECK_PASTESPDRA            1109
#define IDC_GROUP_REFXOBJ               1110
#define IDC_TXT_CROSSTYPE               1111
#define IDC_TXT_XOBJ_UK                 1112
#define IDC_TXT_XOBJ_ANIM_MEM           1113
#define IDC_GROUP_ANIMDATA              1114
#define IDC_EDIT_ANIM_X                 1115
#define IDC_TXT_ANIM_X                  1116
#define IDC_EDIT_ANIM_Y                 1117
#define IDC_TXT_ANIM_Y                  1118
#define IDC_EDIT_ANIM_Z                 1119
#define IDC_TXT_ANIM_Z                  1120
#define IDC_EDIT_ANIM_M1                1121
#define IDC_TXT_ANIM_M1                 1122
#define IDC_EDIT_ANIM_M3                1123
#define IDC_TXT_ANIM_M3                 1124
#define IDC_TXT_ANIML                   1125
#define IDC_TXT_XOBJ_ANIMDELAY          1126
#define IDC_BUTTON_ANIM_EXPORT          1127
#define IDC_BUTTON_ANIM_IMPORT          1128
#define IDC_TXT_FILE_FORMAT             1128
#define IDC_EDIT_ANIM_M2                1129
#define IDC_TXT_NBLOCKS                 1129
#define IDC_TXT_ANIM_M2                 1130
#define IDC_EDIT_FILE_FORMAT            1130
#define IDC_EDIT_ANIM_M4                1131
#define IDC_EDIT_NBLOCKS                1131
#define IDC_TXT_ANIM_M4                 1132
#define IDC_TXT_NBLOCKS2                1132
#define IDC_TXT_XOBJ_UK3                1133
#define IDC_EDIT_NVROAD                 1133
#define IDC_CHECK_CONVERT_GLOBAL        1134
#define IDC_LIST                        1150
#define IDC_CHECK_VROAD                 1151
#define IDC_BLOCK_RADIO1                1154
#define IDC_BLOCK_RADIO2                1155
#define IDC_EDIT_STARTBL                1156
#define IDC_CHECK_TRACK                 1157
#define IDC_CHECK_POLYOBJ               1158
#define IDC_CHECK_EXTRAOBJ              1159
#define IDC_EDIT_TEXTURE                1160
#define IDC_BUTTON_SELECT_TEXTURE       1161
#define IDC_CHECK_TEXTURE               1162
#define IDC_CHECK_HSTEXTURE             1163
#define IDC_BUTTON_SELECT_PVRFLAGS      1164
#define IDC_CHECK_CONVERT_POLY          1164
#define IDC_RADIO_ADD_REPLACE2          1165
#define IDC_TRBLFROMTO3                 1167
#define IDC_TRBLFROMTO1                 1168
#define IDC_TRBLFROMTO2                 1169
#define IDC_EDIT_NUMBLOCKS              1170
#define IDC_EDIT_START                  1171
#define ID_VIEW_ZOOMIN                  32794
#define ID_VIEW_ZOOMOUT                 32795
#define ID_VIEW_ROTATE                  32798
#define ID_VIEW_HEIGHT                  32800
#define ID_MODE_BLOCK                   32801
#define ID_MODE_POINT                   32802
#define ID_MODE_EXTPOINT                32803
#define ID_MODE_OBJECT                  32804
#define ID_MODE_POLYGON                 32805
#define ID_MODE_SMOOTHING               32806
#define ID_TOOLS_MOVEXY                 32808
#define ID_TOOLS_MOVEZ                  32809
#define ID_TOOLS_TEXTURE                32813
#define ID_VIEW_FULLRES                 32815
#define ID_VIEW_HALFRES                 32816
#define ID_VIEW_LOWRES                  32817
#define ID_VIEW_NODESONLY               32818
#define ID_TOOLS_DELETE                 32819
#define ID_TOOLS_DUPLICATE              32820
#define ID_TOOLS_PROPERTIES             32821
#define ID_VIEW_SHOWHIDEOBJECTS         32822
#define ID_VIEW_RECENTER                32826
#define ID_VIEW_REFRESH                 32827
#define ID_VIEW_SHOWLANES               32828
#define ID_EDITMODES_EXTRASMOOTHING     32829
#define ID_TOOLS_MERGE                  32830
#define ID_TOOLS_POLYFLAG               32832
#define ID_TOOLS_ADJUSTWIDTH            32833
#define ID_TOOLS_CLEARALL               32834
#define IDC_TRACKVIEW                   32835
#define ID_VIEW_SHOWTRACK               32836
#define ID_VIEW_VROAD                   32837
#define ID_CORDINATES                   32838
#define ID_Tools_Neighbours             32840
#define ID_EXPORT_VIS                   32841
#define ID_IMPORT_VIS                   32842
#define ID_COPY_Z                       32843
#define ID_COPY_Zh                      32843
#define ID_COPY_Zl                      32844
#define ID_Paste_Zh                     32845
#define ID_PASTE_Zl                     32846
#define ID_MEMZ_AVERAGE                 32847
#define ID_EXPORT_TRKVERTICES           32848
#define ID_EXPORT_QUADS                 32849
#define ID_EXPORT_TEXTURE               32849
#define ID_MODE_VROADEDIT               32850
#define ID_TOOLS_EDITVROAD              32852
#define ID_TOOLS_VROAD_HEIGHTS_SPDFILES 32852
#define ID_COPY_MODE                    32853
#define ID_VIEW_EDITBLOCK               32854
#define ID_VIEW_POLYFLAG                32855
#define ID_TOOLS_LODGEN                 32857
#define ID_VIRTUALROADMASK              32859
#define ID_VIRTUALROADEDGEMASK          32860
#define ID_NONPASSABLEPOLYGONMASK       32862
#define ID_IMPORT_TEXTURE               32863
#define ID_VIRROADBITMAP                32864
#define ID_VIEW_NORMALS                 32865
#define ID_TOOLS_SHADOWRAYTRACER        32866
#define ID_COPY_XY                      32868
#define ID_PASTE_XY                     32869
#define ID_EDIT_PASTE_SHADER            32871
#define ID_EDIT_PASTE_AVERAGE           32872
#define ID_EDIT_PASTE_NORMAL            32873
#define ID_EDIT_COPY_XY                 32874
#define ID_EDIT_PASTE_XY                32875
#define ID_TOOLS_EXPAND                 32876
#define ID_EDITMODES_AUTOOBJMEMBER      32877
#define ID_TOOLS_ROTATE                 32878
#define ID_EDIT_UNDO_KEEP_VR            32879
#define ID_TOOLS_MOVETO                 32880
#define ID_EDIT_PASTE_LINE_XY           32881
#define ID_EDIT_PASTE_LINE_XYZ          32882
#define ID_IMPORT_OBJECT                32883
#define ID_EXPORT_OBJECT                32884
#define ID_TOOLS_INVERT                 32885
#define ID_FILE_PROPERTIES              32886
#define ID_EDIT_MERGE                   32887
#define ID_SET_VIS                      32890
#define ID_VIEW_VISIBILITY              32891
#define ID_VIS_FW_INCREASE              32893
#define ID_VIS_FW_DECREASE              32894
#define ID_VIS_BW_INCREASE              32895
#define ID_VIS_BW_DECREASE              32896
#define ID_VIEW_ZOOMIN3D                32897
#define ID_VIEW_ZOOMOUT3D               32898

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32899
#define _APS_NEXT_CONTROL_VALUE         1172
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
